'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {parseMockExecutionNotice:notice}=require('../services/kisExecutionNoticeReadOnly');
const {parseMockTradeHistory:history}=require('../services/kisTradeHistoryReadOnly');
const {reconcileMockExecutions:reconcile}=require('../services/kisExecutionReconciliation');
const payload=(extra={})=>({ODER_NO:'123',OODER_NO:'000',SELN_BYOV_CLS:'02',ODER_KIND:'00',ODER_COND:'0',STCK_SHRN_ISCD:'005930',CNTG_QTY:'1',CNTG_UNPR:'100',STCK_CNTG_HOUR:'100000',RFUS_YN:'0',CNTG_YN:'2',ACPT_YN:'2',BRNC_NO:'001',ODER_QTY:'10',ORD_EXG_GB:'1',...extra});
const ws=(extra={},id='fixture1',config={})=>notice({provenance:'MOCK_FIXTURE',environment:'KIS_LIVE',uniqueFixtureMessageId:id,payload:payload(extra),...config});
const row=(extra={})=>({pdno:'005930',sll_buy_dvsn_cd:'02',odno:'123',ord_dt:'20260922',ord_tmd:'100000',tot_ccld_qty:'1',avg_prvs:'100',...extra});
const rest=(rows=[row()],code='D')=>history({operation:'DAILY_EXECUTIONS',environment:'KIS_LIVE',provenance:'MOCK_FIXTURE',pages:[{operation:'DAILY_EXECUTIONS',environment:'KIS_LIVE',provenance:'MOCK_FIXTURE',headers:{tr_cont:code},body:{rt_cd:'0',output1:rows,ctx_area_fk100:'fixture',ctx_area_nk100:'next'}}]});
const run=(extra={})=>reconcile({provenance:'MOCK_FIXTURE',wsNotices:[ws()],restHistory:rest(),systemOrderRegistry:[{orderId:'123',symbol:'005930',side:'BUY'}],wsSessionComplete:true,reconnectOccurred:false,gapPossible:false,...extra});
test('execution only for 2',()=>assert.equal(ws().candidate.kind,'EXECUTION_CANDIDATE'));
test('receipt never counted',()=>{const n=ws({CNTG_YN:'1',CNTG_QTY:'999',CNTG_UNPR:'bad'});assert.equal(n.candidate.kind,'RECEIPT_CANDIDATE');assert.equal(n.candidate.quantity,null);assert.equal(run({wsNotices:[n]}).orders[0].status,'WS_ORDER_MISSING');});
for(const [code,side] of [['01','SELL'],['02','BUY']])test('side '+side,()=>assert.equal(ws({SELN_BYOV_CLS:code}).candidate.side,side));
for(const value of [null,'',0,-1,Infinity,NaN,'1e2','1\n',1.2])test('invalid quantity '+String(value),()=>assert.equal(ws({CNTG_QTY:value}).valid,false));
for(const value of [null,'',0,-1,Infinity,'bad'])test('invalid price '+String(value),()=>assert.equal(ws({CNTG_UNPR:value}).valid,false));
test('unknown ids/dates/costs stay null',()=>{const c=ws({eventId:'fake',tradeDate:'20260922'}).candidate;for(const k of ['eventId','fillId','tradeDate','fullTimestamp','verifiedCosts','realizedPnl'])assert.equal(c[k],null);assert.equal(c.costsVerified,false);});
test('weighted order aggregate',()=>{const r=run({wsNotices:[ws({CNTG_QTY:'2',CNTG_UNPR:'100'},'a'),ws({CNTG_QTY:'1',CNTG_UNPR:'130'},'b')],restHistory:rest([row({tot_ccld_qty:'3',avg_prvs:'110'})])});assert.equal(r.orders[0].wsQuantity,3);assert.equal(r.orders[0].wsAveragePrice,110);assert.equal(r.orders[0].status,'MATCHED_AGGREGATE');assert.equal(r.ledgerInputReady,false);assert.equal(r.individualFillComplete,false);});
test('quantity mismatch',()=>assert.equal(run({restHistory:rest([row({tot_ccld_qty:'2'})])}).orders[0].status,'QUANTITY_MISMATCH'));
test('price mismatch',()=>assert.equal(run({restHistory:rest([row({avg_prvs:'101'})])}).orders[0].status,'PRICE_MISMATCH'));
test('REST missing',()=>assert.equal(run({restHistory:rest([])}).orders[0].status,'REST_ORDER_MISSING'));
test('WS missing',()=>assert.equal(run({wsNotices:[]}).orders[0].status,'WS_ORDER_MISSING'));
test('mock duplicate id deduplication',()=>{const n=ws();assert.equal(run({wsNotices:[n,n]}).orders[0].wsQuantity,1);});
test('same content distinct fixture ids not deduplicated',()=>assert.equal(run({wsNotices:[ws({},'a'),ws({},'b')]}).orders[0].wsQuantity,2));
test('same id different payload fails',()=>assert.ok(run({wsNotices:[ws(),ws({CNTG_UNPR:'101'})]}).reasonCodes.includes('FIXTURE_ID_CONFLICT')));
test('missing fixture id does not imply unique',()=>assert.equal(run({wsNotices:[ws({},null)]}).orders[0].status,'IDENTITY_UNVERIFIED'));
for(const extra of [{reconnectOccurred:true},{gapPossible:true},{wsSessionComplete:false},{gapPossible:undefined},{reconnectOccurred:undefined}])test('coverage uncertain '+JSON.stringify(extra),()=>{const r=run(extra);assert.equal(r.status,'INCOMPLETE');assert.equal(r.restReconciliationComplete,false);assert.equal(r.ledgerInputReady,false);});
test('external/unmatched order preserved',()=>{const r=run({systemOrderRegistry:[]});assert.equal(r.orders.length,1);assert.equal(r.orders[0].systemOrderMatched,false);assert.ok(r.reasonCodes.includes('EXTERNAL_TRADE_ORIGIN_UNVERIFIED'));});
test('registry unknown fails closed',()=>assert.equal(run({systemOrderRegistry:null}).status,'INCOMPLETE'));
test('lineage preserved not merged',()=>{const n=ws({OODER_NO:'122'});assert.equal(n.candidate.originalOrderId,'122');const r=run({wsNotices:[n]});assert.equal(r.orders[0].status,'IDENTITY_UNVERIFIED');assert.ok(r.reasonCodes.includes('ORDER_LINEAGE_UNVERIFIED'));});
test('duplicate REST order versions ambiguous',()=>assert.equal(run({restHistory:rest([row(),row({tot_ccld_qty:'2'})])}).orders[0].status,'IDENTITY_UNVERIFIED'));
test('symbol identity collision',()=>assert.equal(run({wsNotices:[ws({STCK_SHRN_ISCD:'000660'})]}).orders[0].status,'IDENTITY_UNVERIFIED'));
test('REST incomplete',()=>assert.equal(run({restHistory:rest([],'F')}).status,'INCOMPLETE'));
for(const provenance of ['PAPER','KIS_NETWORK'])test('provenance rejected '+provenance,()=>{assert.equal(ws({},'a',{provenance}).valid,false);assert.equal(run({provenance}).status,'INCOMPLETE');});
test('LIVE/VTS mismatch',()=>assert.equal(run({wsNotices:[ws({},'a',{environment:'KIS_VTS'})]}).status,'INCOMPLETE'));
test('forged WS result rejected',()=>assert.equal(run({wsNotices:[{...ws()}]}).status,'INCOMPLETE'));
test('forged REST result rejected',()=>assert.equal(run({restHistory:{...rest()}}).status,'INCOMPLETE'));
test('numeric overflow fails',()=>{const n=ws({CNTG_QTY:String(Number.MAX_SAFE_INTEGER),ODER_QTY:String(Number.MAX_SAFE_INTEGER),CNTG_UNPR:'2'});assert.ok(run({wsNotices:[n]}).reasonCodes.includes('AGGREGATE_NUMERIC_INVALID'));});
test('no tolerances or rounded match',()=>assert.equal(run({restHistory:rest([row({avg_prvs:'100.00001'})])}).orders[0].status,'PRICE_MISMATCH'));
test('no raw sensitive fields projected',()=>{const marker='dummy-private-marker',n=ws({CANO:marker,ACNT_NO:marker,approval_key:marker,raw:marker});assert.ok(!JSON.stringify(n).includes(marker));assert.ok(!JSON.stringify(run({wsNotices:[n]})).includes(marker));});
test('readonly results',()=>{const n=ws();assert.throws(()=>{n.candidate.quantity=99;},TypeError);assert.equal(run().riskReady,false);});
test('unknown notice rejected',()=>assert.equal(ws({CNTG_YN:'3'}).valid,false));
test('no network or ledger/risk/paper dependency',()=>{const fs=require('node:fs');for(const name of ['kisExecutionNoticeReadOnly','kisExecutionReconciliation']){const src=fs.readFileSync(require.resolve('../services/'+name),'utf8');assert.doesNotMatch(src,/\bfetch\s*\(|axios|process\.env|console\.|liveRiskLedger|riskManager|paperTrading|createHash|writeFile/);}});
