'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createTestTimeContext:context,createTestTimedSnapshot:issue,createTestTimePolicy:policy,evaluateSnapshotTime:evaluate,isTestSnapshotTimeResult}=require('../services/liveSnapshotCoherence');
function fixture(change={},slot='account') {
  const accountContext=context();
  const base={mode:'KIS_LIVE',environment:'KIS_LIVE',provenance:'TEST_LIVE_FIXTURE',accountContext,currency:'KRW',snapshotId:'mock-bundle',businessDate:'20260922',businessDateStatus:'VERIFIED',sourceTimestamp:'2026-09-22T10:00:00+09:00',sourceTimeStatus:'VERIFIED',receivedAt:'2026-09-22T10:00:01+09:00'};
  return {accountContext,account:issue({...base,...(slot==='account'?change:{})}),portfolio:issue({...base,...(slot==='portfolio'?change:{})}),dailyRisk:issue({...base,...(slot==='dailyRisk'?change:{})}),evaluatedAt:'2026-09-22T10:00:02+09:00',
    freshnessPolicy:policy({kind:'FRESHNESS',status:'VERIFIED',source:'TEST_POLICY',maxAgeMs:3000,provenance:'TEST_LIVE_FIXTURE'}),
    coherencePolicy:policy({kind:'COHERENCE',status:'VERIFIED',source:'TEST_POLICY',maxSourceSkewMs:0,provenance:'TEST_LIVE_FIXTURE'})};
}
test('verified mock policies evaluate but never activate LIVE',()=>{const r=evaluate(fixture());assert.equal(r.freshnessStatus,'VERIFIED');assert.equal(r.coherence,true);assert.equal(r.riskReady,false);assert.equal(r.liveInputAccepted,false);assert.equal(isTestSnapshotTimeResult(r),true);assert.equal(isTestSnapshotTimeResult({...r}),false);});
for(const [key,value,reason] of [['sourceTimestamp',null,'SOURCE_TIMESTAMP_UNVERIFIED'],['sourceTimestamp','invalid','SOURCE_TIMESTAMP_UNVERIFIED'],['sourceTimeStatus','UNKNOWN','SOURCE_TIMESTAMP_UNVERIFIED'],['businessDateStatus','UNKNOWN','BUSINESS_DATE_UNVERIFIED'],['businessDate',null,'BUSINESS_DATE_UNVERIFIED'],['businessDate','20260230','BUSINESS_DATE_UNVERIFIED'],['businessDate','20260923','BUSINESS_DATE_MISMATCH'],['currency','USD','CURRENCY_MISMATCH'],['accountContext',context(),'ACCOUNT_IDENTITY_MISMATCH'],['mode','APP_PAPER','ENVIRONMENT_MISMATCH'],['mode','KIS_VTS','ENVIRONMENT_MISMATCH'],['environment','KIS_VTS','ENVIRONMENT_MISMATCH'],['snapshotId','different','SNAPSHOT_COHERENCE_UNVERIFIED'],['receivedAt','invalid','OBSERVATION_TIME_INVALID'],['receivedAt','2026-09-22T09:59:59+09:00','OBSERVATION_TIME_INVALID']])test('reject '+key+' '+String(value),()=>{const r=evaluate(fixture({[key]:value}));assert.equal(r.coherence,false);assert.ok(r.reasonCodes.includes(reason));});
for(const provenance of ['PAPER','KIS_NETWORK','MOCK_FIXTURE',undefined])test('provenance '+provenance,()=>assert.ok(evaluate(fixture({provenance})).reasonCodes.includes('PROVENANCE_MISMATCH')));
test('receivedAt alone cannot prove freshness',()=>assert.equal(evaluate(fixture({sourceTimestamp:null,sourceTimeStatus:null})).freshnessStatus,'UNKNOWN'));
test('evaluatedAt alone cannot prove freshness',()=>assert.equal(evaluate({evaluatedAt:'2026-09-22T10:00:02+09:00'}).freshnessStatus,'UNKNOWN'));
for(const field of ['freshnessPolicy','coherencePolicy'])test('no default '+field,()=>{const f=fixture();delete f[field];const r=evaluate(f);assert.equal(r.coherence,false);assert.ok(r.reasonCodes.includes(field==='freshnessPolicy'?'FRESHNESS_POLICY_UNVERIFIED':'QUERY_TIME_ALIGNMENT_UNVERIFIED'));});
for(const maxAgeMs of [undefined,null,-1,NaN,Infinity,'3000'])test('invalid maxAgeMs '+String(maxAgeMs),()=>{const f=fixture();f.freshnessPolicy=policy({kind:'FRESHNESS',status:'VERIFIED',source:'TEST',maxAgeMs,provenance:'TEST_LIVE_FIXTURE'});assert.equal(evaluate(f).freshnessStatus,'UNKNOWN');});
test('UNKNOWN policy blocks',()=>{const f=fixture();f.freshnessPolicy=policy({...f.freshnessPolicy,status:'UNKNOWN'});assert.equal(evaluate(f).freshnessStatus,'UNKNOWN');});
test('stale blocks',()=>{const f=fixture();f.evaluatedAt='2026-09-22T10:00:04+09:00';assert.equal(evaluate(f).freshnessStatus,'STALE');assert.equal(evaluate(f).coherence,false);});
test('future source blocks',()=>{const f=fixture();f.evaluatedAt='2026-09-22T09:59:59+09:00';assert.equal(evaluate(f).freshnessStatus,'UNKNOWN');});
test('invalid evaluation time blocks',()=>{const f=fixture();f.evaluatedAt=null;assert.equal(evaluate(f).freshnessStatus,'UNKNOWN');});
test('identical receipts do not align unequal sources',()=>{const r=evaluate(fixture({sourceTimestamp:'2026-09-22T09:59:59+09:00'}));assert.equal(r.queryTimeAlignmentVerified,false);});
test('explicit test skew policy evaluates unequal sources',()=>{const f=fixture({sourceTimestamp:'2026-09-22T09:59:59+09:00'});f.coherencePolicy=policy({...f.coherencePolicy,maxSourceSkewMs:1000});assert.equal(evaluate(f).coherence,true);assert.equal(evaluate(f).riskReady,false);});
test('queryDate is not a substitute',()=>assert.equal(issue({provenance:'TEST_LIVE_FIXTURE',accountContext:context(),queryDate:'20260922'}),null));
test('copied snapshot and policy lose markers',()=>{for(const key of ['account','freshnessPolicy','coherencePolicy']){const f=fixture();f[key]={...f[key]};assert.equal(evaluate(f).coherence,false);}});
test('sensitive extras not returned',()=>{const f=fixture();f.secret='DUMMY_PRIVATE';assert.ok(!JSON.stringify(evaluate(f)).includes('DUMMY_PRIVATE'));assert.equal(issue({provenance:'TEST_LIVE_FIXTURE',accountContext:context(),CANO:'DUMMY_PRIVATE'}),null);});
test('only pure time dependency; no boundary or risk call',()=>{const source=require('node:fs').readFileSync(require.resolve('../services/liveSnapshotCoherence'),'utf8');assert.deepEqual([...source.matchAll(/require\('([^']+)'\)/g)].map(m=>m[1]),['./dataFreshness']);assert.ok(!/process\.env|Date\.now|fetch\(|evaluateRisk\(/.test(source));});
