'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createMockLiveRiskLedgerRepository:repo}=require('../services/liveRiskLedgerRepository');
const {createLiveRiskLedgerPersistence:engine}=require('../services/liveRiskLedgerPersistence');
const {createTestExternalAccountContext:context,createTestExternalTradeInput:issue}=require('../services/liveExternalTradePolicy');
const at='2026-09-22T10:00:00+09:00',day='2026-09-22';
function bootstrap(change={}){return issue({mode:'KIS_LIVE',environment:'KIS_LIVE',provenance:'TEST_LIVE_FIXTURE',accountContext:context(),businessDate:day,businessDateVerified:true,startPolicy:'CLEAN_START',currentPositions:[],positionsComplete:true,positionsAtStartVerified:true,pendingOrders:[],pendingOrdersComplete:true,pendingOrdersAtStartVerified:true,tradeHistoryCandidates:[],systemOrderRegistry:[],historyComplete:true,registryComplete:true,reentryHistoryVerified:true,...change});}
function config(repository,extra={}){return {repository,accountContextId:'TEST_ACCOUNT_A',businessDate:day,businessDateVerified:true,bootstrapInput:bootstrap(),initialConsecutiveLosses:0,initialConsecutiveLossesVerified:true,persistedAt:at,...extra};}
function fill(change={}){return {provenance:'TEST_LIVE_FIXTURE',eventId:'TEST_EVENT_A',orderId:'TEST_ORDER_A',symbol:'005930',side:'BUY',quantity:2,price:100,costAmount:0,costsVerified:true,sequence:1,businessDate:day,businessDateVerified:true,historyVerified:true,sequenceVerified:true,...change};}
test('clean bootstrap and isolated memory save/load',()=>{const r=repo(),e=engine(config(r));assert.equal(e.getStatus().status,'RECOVERY_READY');assert.equal(e.getState().stateVersion,1);assert.equal(e.getState().ledger.lossAmount,0);assert.equal(e.getStatus().persistence,'MEMORY_ONLY');assert.ok(e.getStatus().reasonCodes.includes('PERSISTENCE_NOT_DURABLE'));});
for(const startPolicy of ['UNKNOWN_START','MANAGED_EXISTING_POSITION'])test('bootstrap rejects '+startPolicy,()=>{const r=repo();assert.equal(engine(config(r,{bootstrapInput:bootstrap({startPolicy})})).getStatus().status,'RECOVERY_FAILED');assert.equal(r.loadState(),null);});
test('unverified initial streak not default zero',()=>assert.equal(engine(config(repo(),{initialConsecutiveLosses:null})).getStatus().status,'RECOVERY_FAILED'));
test('normal events, open cycle, completed cycle and loss recovered',()=>{const r=repo(),c=config(r),e=engine(c);assert.equal(e.applyEvent(fill(),at).status,'EVENT_COMMITTED');assert.equal(e.getState().stateVersion,2);assert.equal(engine(c).getState().ledger.openPositions[0].quantity,2);e.applyEvent(fill({eventId:'TEST_EVENT_B',side:'SELL',price:90,sequence:2}),at);const recovered=engine(c).getState();assert.equal(recovered.ledger.lossAmount,20);assert.equal(recovered.ledger.consecutiveLosses,1);assert.equal(recovered.ledger.completedCycles.length,1);assert.equal(recovered.ledger.openPositions.length,0);});
test('write failure never advances either state',()=>{let fail=false;const r=repo({beforeCommit:()=>{if(fail)throw Error('DUMMY_SECRET');}}),e=engine(config(r)),before=e.getState();fail=true;const result=e.applyEvent(fill(),at);assert.equal(result.status,'RECOVERY_FAILED');assert.ok(!JSON.stringify(result).includes('DUMMY_SECRET'));assert.deepEqual(e.getState(),before);assert.deepEqual(r.loadState(),before);});
test('duplicate across restart preserves version, field order immaterial',()=>{const r=repo(),c=config(r),e=engine(c);e.applyEvent(fill(),at);const recovered=engine(c);assert.equal(recovered.applyEvent(Object.fromEntries(Object.entries(fill()).reverse()),at).status,'DUPLICATE_IGNORED');assert.equal(recovered.getState().stateVersion,2);});
test('duplicate conflicting payload blocks future mutations',()=>{const e=engine(config(repo()));e.applyEvent(fill(),at);assert.equal(e.applyEvent(fill({price:99}),at).status,'RECOVERY_FAILED');assert.equal(e.applyEvent(fill({eventId:'TEST_NEW',sequence:2}),at).status,'RECOVERY_FAILED');assert.equal(e.getState().stateVersion,2);});
for(const [name,corrupt] of [
  ['schema',s=>{s.schemaVersion=2;}],['missing version',s=>{delete s.stateVersion;}],['negative version',s=>{s.stateVersion=-1;}],['same version altered data',s=>{s.ledger.lossAmount=9;}],['account',s=>{s.accountContextId='TEST_ACCOUNT_B';}],['environment',s=>{s.environment='KIS_VTS';}],['date',s=>{s.businessDate='2026-09-23';}],['loss null',s=>{s.ledger.lossAmount=null;}],['loss negative',s=>{s.ledger.lossAmount=-1;}],['streak invalid',s=>{s.ledger.consecutiveLosses=NaN;}],['open cycle',s=>{s.ledger.openPositions[0].quantity=99;}],['processed ids',s=>{s.processedEventIds=[];}],['duplicate event',s=>{s.events.push({...s.events[0],price:99});}],['paper schema',s=>{s.namespace='PAPER';}],['unknown key',s=>{s.CANO='DUMMY_PRIVATE';}]
])test('recovery corruption '+name,()=>{let corruptNow=false;const r=repo({readTransform:s=>{if(s&&corruptNow)corrupt(s);return s;}}),c=config(r);engine(c).applyEvent(fill(),at);corruptNow=true;const e=engine(c);assert.equal(e.getStatus().status,'RECOVERY_FAILED');assert.equal(e.getState(),null);});
test('malformed JSON read not repaired',()=>{const r=repo({readTransform:()=>'{broken'});assert.equal(engine(config(r)).getStatus().status,'RECOVERY_FAILED');});
test('requested account mismatch blocked',()=>{const r=repo();engine(config(r));assert.equal(engine(config(r,{accountContextId:'TEST_ACCOUNT_B'})).getStatus().status,'RECOVERY_FAILED');});
test('requested date mismatch blocked',()=>{const r=repo();engine(config(r));assert.equal(engine(config(r,{businessDate:'2026-09-23'})).getStatus().status,'RECOVERY_FAILED');});
test('stale writer cannot overwrite newer version',()=>{const r=repo(),c=config(r),a=engine(c),b=engine(c);a.applyEvent(fill(),at);assert.equal(b.applyEvent(fill({eventId:'TEST_OTHER'}),at).status,'RECOVERY_FAILED');assert.equal(r.loadState().events[0].eventId,'TEST_EVENT_A');});
for(const change of [{provenance:'KIS_NETWORK'},{provenance:'PAPER'},{eventId:'REAL_UNKNOWN'}, {quantity:null},{price:Infinity},{costsVerified:false},{businessDate:'2026-09-23'},{CANO:'DUMMY_PRIVATE'}])test('event rejected '+Object.keys(change).join(),()=>{const r=repo(),e=engine(config(r));const result=e.applyEvent(fill(change),at);assert.equal(result.status,'EVENT_REJECTED');if(change.provenance==='KIS_NETWORK')assert.ok(result.reasonCodes.includes('EVENT_ID_UNVERIFIED'));assert.equal(r.loadState().stateVersion,1);assert.ok(!JSON.stringify(r.loadState()).includes('DUMMY_PRIVATE'));});
test('paper and arbitrary repository refused',()=>assert.equal(engine(config({persistence:'MEMORY_ONLY',loadState:()=>null})).getStatus().status,'RECOVERY_FAILED'));
test('rollover proposal preserves old date and open cycles; streak carried',()=>{const e=engine(config(repo(),{initialConsecutiveLosses:2}));e.applyEvent(fill(),at);const before=e.getState(),r=e.proposeRollover({businessDate:'2026-09-23',businessDateVerified:true});assert.equal(r.status,'ROLLOVER_CANDIDATE');assert.equal(r.applied,false);assert.equal(r.dailyLossCandidate,0);assert.equal(r.consecutiveLossesCandidate,2);assert.deepEqual(e.getState(),before);assert.equal(e.proposeRollover({businessDate:day,businessDateVerified:true}).status,'ROLLOVER_UNCHANGED');});
for(const change of [{businessDate:'2026-09-21',businessDateVerified:true},{businessDate:'2026-09-23'},{businessDate:'invalid',businessDateVerified:true}])test('invalid rollover '+JSON.stringify(change),()=>assert.equal(engine(config(repo())).proposeRollover(change).status,'ROLLOVER_REJECTED'));
test('risk flags never activate and no network/paper/risk dependency',()=>{const r=engine(config(repo())).getStatus();assert.equal(r.riskReady,false);assert.equal(r.ledgerInputReady,false);for(const file of ['liveRiskLedgerState','liveRiskLedgerRepository','liveRiskLedgerPersistence']){const s=require('node:fs').readFileSync(require.resolve('../services/'+file),'utf8');assert.ok(!/paperTrading|riskManager|process\.env|fetch\(|Date\.now|postgres/i.test(s));}});
