'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {createPaperTrading,evaluatePaperExitSignal}=require('../services/paperTrading');
const {buildRiskContext,evaluateRiskWithSnapshots}=require('../services/accountSnapshot');
const {calculateTradingStrategy}=require('../services/tradingStrategy');
// Explicit synthetic capital, prices, policy and timestamps. Never live market data.
const stamp=()=>({source:'MOCK_EXECUTION',sourceTimestamp:'2026-09-21T10:00:00+09:00',businessDate:'2026-09-21',receivedAt:null});
const initial=()=>{const m={...stamp(),snapshotId:'MOCK-INITIAL',complete:true,currency:'KRW'};return {
 accountSnapshot:{...m,equity:10000,availableCash:10000},portfolioSnapshot:{...m,positions:[],pendingOrders:[]},
 dailyRiskState:{...m,lossAmount:0,consecutiveLosses:0}};};
const strategy=()=>calculateTradingStrategy({symbol:'005930',currentPrice:100,chartAnalysis:{ma5:100,ma20:99,ma60:98,rsi14:50,
 macd:{macd:2,signal:1,histogram:1},bollingerBands:{position:50},atr14:10,supportResistance:{nearestSupport:{price:100},nearestResistance:{price:120}}},
 marketContext:{volume:150,averageVolume20:100,foreignerNet:1,institutionNet:1,newsAssessment:{hasCautionSignal:false}}});
const policy=()=>({enabled:true,maxInvestmentPerSymbol:1000,maxOrderAmount:1000,maxDailyLoss:100,maxHoldings:3,
 preventDuplicatePosition:true,preventDuplicatePendingOrder:true,maxConsecutiveLosses:3,maxExposureRatio:0.5});
const book=()=>createPaperTrading({sessionId:'MOCK',initialSnapshots:initial()});
const proposal=(p,patch={})=>{const snapshots=p.getSnapshots(stamp()),s=strategy(),rules=policy();const i={...snapshots,strategyResult:s,symbol:s.symbol,proposedQuantity:4,proposedEntryPrice:100,policy:rules};return {
 clientOrderId:'BUY-1',strategyResult:s,riskResult:evaluateRiskWithSnapshots(i),snapshots,policy:rules,quantity:4,proposedEntryPrice:100,...patch};};
const fill=(eventId,fillPrice=100,fillQuantity=4)=>({...stamp(),eventId,validated:true,fillPrice,fillQuantity});
const opened=()=>{const p=book();assert.equal(p.createEntryOrder(proposal(p)).allowed,true);assert.equal(p.fillPaperOrder('BUY-1',fill('F1')).allowed,true);return p;};
const {createPaperTradingRepository}=require('../services/paperTradingRepository');
const engine=repo=>createPaperTrading({sessionId:'MOCK',initialSnapshots:initial(),repository:repo});
const seeded=()=>{const repo=createPaperTradingRepository(),p=engine(repo);p.createEntryOrder(proposal(p));return {repo,p};};
test('memory repository load/save isolated and explicit mode',()=>{const r=createPaperTradingRepository();assert.equal(r.persistence,'MEMORY_ONLY');r.begin(null);r.saveState({stateVersion:0});r.commit();const x=r.loadState();x.stateVersion=5;assert.equal(r.loadState().stateVersion,0);});
test('pending restart and duplicate client ID',()=>{const {repo}=seeded(),b=engine(repo);assert.equal(b.getOrder('BUY-1').status,'PENDING');assert.equal(b.createEntryOrder(proposal(b)).allowed,false);});
test('partial position and event idempotency survive restart',()=>{const {repo,p}=seeded();p.fillPaperOrder('BUY-1',fill('F',90,1));const b=engine(repo);assert.equal(b.getOrder('BUY-1').status,'PARTIALLY_FILLED');assert.equal(b.getPosition('005930').averageEntryPrice,90);assert.equal(b.fillPaperOrder('BUY-1',fill('F',90,1)).allowed,false);assert.equal(b.fillPaperOrder('BUY-1',fill('F2',100,3)).allowed,true);});
test('realized PnL and daily risk recover',()=>{const {repo,p}=seeded();p.fillPaperOrder('BUY-1',fill('F'));p.createExitOrder({...stamp(),clientOrderId:'S',symbol:'005930',quantity:4});p.fillPaperOrder('S',fill('S',90));const b=engine(repo);assert.equal(b.getPosition('005930').realizedPnl,-40);assert.equal(b.getState().dailyLoss,40);assert.equal(b.getState().consecutiveLosses,1);});
for(const stage of ['saveState','saveEvent','commit'])test('atomic rollback at '+stage,()=>{const {repo,p}=seeded();const b=engine({...repo,[stage]:()=>{throw Error('MOCK_FAILURE');}}),before=repo.loadState();assert.equal(b.fillPaperOrder('BUY-1',fill('F')).allowed,false);assert.deepEqual(repo.loadState(),before);assert.deepEqual(b.exportState(),before);assert.equal(repo.hasProcessedEvent('F'),false);assert.equal(b.persistence,'PERSISTENT_UNAVAILABLE');assert.equal(b.getSnapshots(stamp()).valid,false);assert.equal(b.fillPaperOrder('BUY-1',fill('F2')).allowed,false);});
const corruptions={schema:s=>s.schemaVersion=2,version:s=>s.stateVersion=null,date:s=>s.businessDate='2026-02-30',cash:s=>s.cash=null,nan:s=>s.cash=NaN,infinity:s=>s.cash=Infinity,status:s=>s.orders[0].status='UNKNOWN',quantity:s=>s.orders[0].quantity=null,price:s=>s.orders[0].limitPrice=0,duplicateOrder:s=>s.orders.push({...s.orders[0]}),duplicateClient:s=>s.clientOrderIds.push(s.clientOrderIds[0]),duplicateFill:s=>s.processedEventIds.push('F','F'),position:s=>s.positions.push({symbol:'005930',quantity:null}),timestamp:s=>s.updatedAt=null};
for(const [name,change] of Object.entries(corruptions))test('corrupt recovery blocked '+name,()=>{const {repo}=seeded();const state=repo.loadState();change(state);assert.throws(()=>engine({...repo,loadState:()=>state}),/RECOVERY_FAILED/);});
test('zero preserved on recovery',()=>{const r=createPaperTradingRepository(),i=initial();i.accountSnapshot.equity=0;i.accountSnapshot.availableCash=0;const options={sessionId:'ZERO',initialSnapshots:i,repository:r};createPaperTrading(options);assert.equal(createPaperTrading(options).getState().cash,0);});
test('rollover idempotent, rejects backwards and missing source time',()=>{const p=book(),before=p.exportState();assert.equal(p.rolloverBusinessDate('2026-09-21').idempotent,true);assert.deepEqual(p.exportState(),before);assert.equal(p.rolloverBusinessDate('2026-09-20',stamp()).allowed,false);assert.equal(p.rolloverBusinessDate('2026-09-22').allowed,false);});
test('rollover preserves pending, partial positions, IDs and separates daily loss',()=>{const {repo,p}=seeded();p.fillPaperOrder('BUY-1',fill('F',100,1));const before=p.exportState();const next={...stamp(),sourceTimestamp:'2026-09-22T10:00:00+09:00',businessDate:'2026-09-22'};assert.equal(p.rolloverBusinessDate(next.businessDate,next).allowed,true);const b=engine(repo),after=b.exportState();assert.deepEqual(after.orders,before.orders);assert.deepEqual(after.positions,before.positions);assert.deepEqual(after.processedEventIds,before.processedEventIds);assert.equal(after.dailyRiskHistory.length,1);assert.equal(b.fillPaperOrder('BUY-1',{...fill('F2',100,3),...next}).allowed,true);});
test('rollover resets only daily loss and preserves streak/PnL',()=>{const {repo,p}=seeded();p.fillPaperOrder('BUY-1',fill('F'));p.createExitOrder({...stamp(),clientOrderId:'S',symbol:'005930',quantity:4});p.fillPaperOrder('S',fill('S',90));p.rolloverBusinessDate('2026-09-22',{...stamp(),sourceTimestamp:'2026-09-22T10:00:00+09:00'});const b=engine(repo);assert.equal(b.getState().dailyLoss,0);assert.equal(b.getState().consecutiveLosses,1);assert.equal(b.getPosition('005930').realizedPnl,-40);assert.equal(b.exportState().dailyRiskHistory[0].lossAmount,40);});
test('recovered snapshot requires explicit valuation and stays UNKNOWN',()=>{const {repo,p}=seeded();p.fillPaperOrder('BUY-1',fill('F'));const b=engine(repo);assert.equal(b.getSnapshots(stamp()).valid,false);const r=b.getSnapshots({...stamp(),marks:{'005930':{...stamp(),validated:true,price:100}}});assert.equal(r.valid,true);assert.equal(r.accountSnapshot.freshnessStatus,'UNKNOWN');});
test('concurrent stale writer fails closed without overwriting',()=>{const {repo,p}=seeded(),b=engine(repo);p.fillPaperOrder('BUY-1',fill('F',100,1));assert.equal(b.fillPaperOrder('BUY-1',fill('F2',100,1)).allowed,false);assert.equal(repo.loadState().orders[0].filledQuantity,1);});
test('postgres requested without configuration never falls back',()=>{assert.throws(()=>createPaperTradingRepository({mode:'POSTGRES'}),/PERSISTENT_UNAVAILABLE/);});
test('asynchronous repositories cannot be mistaken for committed writes',()=>{const r=createPaperTradingRepository();assert.throws(()=>engine({...r,commit:async()=>{}}),/PERSISTENT_UNAVAILABLE/);});
test('missing committed event journal blocks recovery',()=>{const {repo,p}=seeded();p.fillPaperOrder('BUY-1',fill('F'));assert.throws(()=>engine({...repo,hasProcessedEvent:()=>false}),/RECOVERY_FAILED/);});
test('changed seed cannot silently redefine recovered capital',()=>{const {repo}=seeded(),i=initial();i.accountSnapshot.equity=20000;i.accountSnapshot.availableCash=20000;assert.throws(()=>createPaperTrading({sessionId:'MOCK',initialSnapshots:i,repository:repo}),/RECOVERY_FAILED/);});
test('duplicate or invalid recovered positions fail closed',()=>{const {repo,p}=seeded();p.fillPaperOrder('BUY-1',fill('F'));for(const mutate of [s=>s.positions.push({...s.positions[0]}),s=>s.positions[0].averageEntryPrice=null,s=>s.positions[0].quantity=5]){const state=repo.loadState();mutate(state);assert.throws(()=>engine({...repo,loadState:()=>state}),/RECOVERY_FAILED/);}});
test('failed rollover cannot reset committed daily state',()=>{const {repo}=seeded(),p=engine({...repo,saveState:()=>{throw Error('FAIL');}}),before=repo.loadState();assert.equal(p.rolloverBusinessDate('2026-09-22',{...stamp(),sourceTimestamp:'2026-09-22T10:00:00+09:00'}).allowed,false);assert.deepEqual(repo.loadState(),before);assert.deepEqual(p.exportState(),before);});
test('load failure is not an empty ledger or memory fallback',()=>{assert.throws(()=>engine({...createPaperTradingRepository(),loadState:()=>{throw Error('UNAVAILABLE');}}),/RECOVERY_FAILED/);});
test('repository/state modules have no database network or environment dependency',()=>{for(const file of ['paperTradingRepository','paperTradingState']){let calls=0;const forbidden=()=>{calls++;throw Error('NO_IO');},module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../services/'+file),'utf8'),{module,structuredClone,require:name=>{assert.equal(name,'./dataFreshness');return require('../services/dataFreshness');},fetch:forbidden,process:new Proxy({},{get:forbidden})});if(file==='paperTradingRepository'){const r=module.exports.createPaperTradingRepository();r.begin(null);r.saveState({stateVersion:0});r.commit();assert.equal(r.loadState().stateVersion,0);}assert.equal(calls,0);}});
