'use strict';

const DAILY_CANDIDATE_MODE='DAILY_TECHNICAL_CANDIDATE_V1';
const DERIVED_CALCULATOR_VERSION='OBSERVATION_DAILY_INPUTS_V1';
module.exports={DAILY_CANDIDATE_MODE,DERIVED_CALCULATOR_VERSION};
